### ISSUE TITLE
"loading" attribute in useWeb3 hook

### ISSUE THREAD

**Issue by davidivad96** [nftlabs/ui#43]
It would be great if we could know when the useWeb3 hook has finished loading all the data.

I would like to display a loading spinner while the data is being retrieved from useWeb3 hook and I don't have an easy way to do this. Right now I'm using a `setTimeout` function but this is obviously not a good way of doing it.

**Comment by davidivad96** [comment]
Ok, I've just found a way to detect when the data has been loaded. Just check that `balance?.formatted` exists. If it's true, then the data has finished loading, whatever a wallet is connected or not.

**Comment by vamsitallam** [comment]
HI @davidivad96 

In some cases, even if balance?.formatted exists, the complete useWeb3 is not loaded.

Is there any other way to achieve this?

Or, Could you please add loading attribute for this
